### PR TITLE
An idea for scraping events data from Meetup.com

### PR DESCRIPTION
**Pull request by mtranter**
Off the back of @neozenith 's idea to publish a static list of events to S3, I thought maybe we could go one simpler.

I've added a script to fetch the events data at build time. I've also added a basic GH Actions script to run this nightly and push the changes back to `master`

To really work, this script should also auto-deploy the app in its entirety.

ref: https://github.com/newwwie/newwwie.com/issues/50

### CODE REVIEW

**Review by neozenith — COMMENTED** [review]
Looks good. What is needed next here?

**Comment by mtranter** [comment]
Hmm.. Looks like this is hosted by github pages? I guess nothing needs to be done then. Is newwwie.com served from `master` ? If so, we can just merge this, if we're happy, and it should be all good.

**Comment by neozenith** [comment]
Yeah it’s all served from master.

**Comment by neozenith** [comment]
Let’s merge and see how it goes.

**Pull request merged**
